"""Initial migration.

Revision ID: 6159bf2b47dd
Revises:
Create Date: 2025-11-14 16:30:30.247135

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6159bf2b47dd"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

USER_ID = "user.id"
PROVIDER_ID = "provider.id"


def upgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provider",
        sa.Column("status", sa.VARCHAR(length=14), nullable=False),
        sa.Column("expiration_date", sa.DATE(), nullable=True),
        sa.Column("description", sa.VARCHAR(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("type", sa.VARCHAR(length=10), nullable=False),
        sa.Column("auth_endpoint", sa.VARCHAR(length=255), nullable=False),
        sa.Column("is_public", sa.BOOLEAN(), nullable=False),
        sa.Column("support_emails", sqlite.JSON(), nullable=True),
        sa.Column("image_tags", sqlite.JSON(), nullable=True),
        sa.Column("network_tags", sqlite.JSON(), nullable=True),
        sa.Column("rally_username", sa.VARCHAR(), nullable=False),
        sa.Column("rally_password", sa.VARCHAR(), nullable=False),
        sa.Column("floating_ips_enable", sa.BOOLEAN(), nullable=False),
        sa.Column("test_flavor_name", sa.VARCHAR(), nullable=False),
        sa.Column("test_network_id", sa.VARCHAR(), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("id", sa.CHAR(length=32), nullable=False),
        sa.Column("created_by_id", sa.CHAR(length=32), nullable=False),
        sa.Column("updated_by_id", sa.CHAR(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            [USER_ID],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            [USER_ID],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("auth_endpoint"),
        sa.UniqueConstraint("name"),
        if_not_exists=True,
    )
    op.create_table(
        "usergroup",
        sa.Column("description", sa.VARCHAR(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("id", sa.CHAR(length=32), nullable=False),
        sa.Column("created_by_id", sa.CHAR(length=32), nullable=False),
        sa.Column("updated_by_id", sa.CHAR(length=32), nullable=False),
        sa.Column("idp_id", sa.CHAR(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            [USER_ID],
        ),
        sa.ForeignKeyConstraint(
            ["idp_id"], ["identityprovider.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            [USER_ID],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "idp_id", name="unique_name_idp_couple"),
        if_not_exists=True,
    )
    op.create_table(
        "project",
        sa.Column("description", sa.VARCHAR(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("iaas_project_id", sa.VARCHAR(), nullable=False),
        sa.Column("is_root", sa.BOOLEAN(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("id", sa.CHAR(length=32), nullable=False),
        sa.Column("created_by_id", sa.CHAR(length=32), nullable=False),
        sa.Column("updated_by_id", sa.CHAR(length=32), nullable=False),
        sa.Column("provider_id", sa.CHAR(length=32), nullable=False),
        sa.Column("sla_id", sa.CHAR(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            [USER_ID],
        ),
        sa.ForeignKeyConstraint(["provider_id"], [PROVIDER_ID], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["sla_id"], ["sla.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            [USER_ID],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "iaas_project_id", "provider_id", name="unique_projid_provider_couple"
        ),
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_unique_provider_root"),
        "project",
        ["provider_id"],
        unique=1,
        sqlite_where=sa.text("is_root = 1"),
        if_not_exists=True,
    )
    op.create_table(
        "evaluates",
        sa.Column("user_id", sa.CHAR(length=32), nullable=False),
        sa.Column("provider_id", sa.CHAR(length=32), nullable=False),
        sa.ForeignKeyConstraint(["provider_id"], [PROVIDER_ID], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            [USER_ID],
        ),
        sa.PrimaryKeyConstraint("user_id", "provider_id"),
        if_not_exists=True,
    )
    op.create_table(
        "administrates",
        sa.Column("user_id", sa.CHAR(length=32), nullable=False),
        sa.Column("provider_id", sa.CHAR(length=32), nullable=False),
        sa.ForeignKeyConstraint(["provider_id"], [PROVIDER_ID], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            [USER_ID],
        ),
        sa.PrimaryKeyConstraint("user_id", "provider_id"),
        if_not_exists=True,
    )
    op.create_table(
        "identityprovider",
        sa.Column("description", sa.VARCHAR(), nullable=False),
        sa.Column("endpoint", sa.VARCHAR(length=255), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("groups_claim", sa.VARCHAR(), nullable=False),
        sa.Column("protocol", sa.VARCHAR(), nullable=True),
        sa.Column("audience", sa.VARCHAR(), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("id", sa.CHAR(length=32), nullable=False),
        sa.Column("created_by_id", sa.CHAR(length=32), nullable=False),
        sa.Column("updated_by_id", sa.CHAR(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            [USER_ID],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            [USER_ID],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("endpoint"),
        if_not_exists=True,
    )
    op.create_table(
        "regionoverrides",
        sa.Column("default_public_net", sa.VARCHAR(), nullable=True),
        sa.Column("default_private_net", sa.VARCHAR(), nullable=True),
        sa.Column("private_net_proxy_host", sa.VARCHAR(), nullable=True),
        sa.Column("private_net_proxy_user", sa.VARCHAR(), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("created_by_id", sa.CHAR(length=32), nullable=False),
        sa.Column("updated_by_id", sa.CHAR(length=32), nullable=False),
        sa.Column("region_id", sa.CHAR(length=32), nullable=False),
        sa.Column("project_id", sa.CHAR(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            [USER_ID],
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["region.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            [USER_ID],
        ),
        sa.PrimaryKeyConstraint("region_id", "project_id"),
        if_not_exists=True,
    )
    op.create_table(
        "region",
        sa.Column("description", sa.VARCHAR(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("overbooking_cpu", sa.FLOAT(), nullable=False),
        sa.Column("overbooking_ram", sa.FLOAT(), nullable=False),
        sa.Column("bandwidth_in", sa.FLOAT(), nullable=False),
        sa.Column("bandwidth_out", sa.FLOAT(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("id", sa.CHAR(length=32), nullable=False),
        sa.Column("created_by_id", sa.CHAR(length=32), nullable=False),
        sa.Column("updated_by_id", sa.CHAR(length=32), nullable=False),
        sa.Column("provider_id", sa.CHAR(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            [USER_ID],
        ),
        sa.ForeignKeyConstraint(["provider_id"], [PROVIDER_ID], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            [USER_ID],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "name", "provider_id", name=op.f("unique_name_provider_couple")
        ),
        if_not_exists=True,
    )
    op.create_table(
        "idpoverrides",
        sa.Column("groups_claim", sa.VARCHAR(), nullable=True),
        sa.Column("name", sa.VARCHAR(), nullable=True),
        sa.Column("protocol", sa.VARCHAR(), nullable=True),
        sa.Column("audience", sa.VARCHAR(), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("created_by_id", sa.CHAR(length=32), nullable=False),
        sa.Column("updated_by_id", sa.CHAR(length=32), nullable=False),
        sa.Column("idp_id", sa.CHAR(length=32), nullable=False),
        sa.Column("provider_id", sa.CHAR(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            [USER_ID],
        ),
        sa.ForeignKeyConstraint(
            ["idp_id"],
            ["identityprovider.id"],
        ),
        sa.ForeignKeyConstraint(["provider_id"], [PROVIDER_ID], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            [USER_ID],
        ),
        sa.PrimaryKeyConstraint("idp_id", "provider_id"),
        if_not_exists=True,
    )
    op.create_table(
        "sla",
        sa.Column("description", sa.VARCHAR(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("url", sa.VARCHAR(length=255), nullable=False),
        sa.Column("start_date", sa.DATE(), nullable=False),
        sa.Column("end_date", sa.DATE(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("id", sa.CHAR(length=32), nullable=False),
        sa.Column("created_by_id", sa.CHAR(length=32), nullable=False),
        sa.Column("updated_by_id", sa.CHAR(length=32), nullable=False),
        sa.Column("user_group_id", sa.CHAR(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            [USER_ID],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            [USER_ID],
        ),
        sa.ForeignKeyConstraint(
            ["user_group_id"], ["usergroup.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
        if_not_exists=True,
    )
    op.create_table(
        "user",
        sa.Column("sub", sa.VARCHAR(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("email", sa.VARCHAR(), nullable=False),
        sa.Column("issuer", sa.VARCHAR(length=255), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("id", sa.CHAR(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sub", "issuer", name=op.f("unique_sub_issuer_couple")),
        if_not_exists=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    op.drop_table("sla")
    op.drop_table("idpoverrides")
    op.drop_table("region")
    op.drop_table("regionoverrides")
    op.drop_table("identityprovider")
    op.drop_table("administrates")
    op.drop_table("evaluates")
    op.drop_index(
        op.f("ix_unique_provider_root"),
        table_name="project",
        sqlite_where=sa.text("is_root = 1"),
    )
    op.drop_table("project")
    op.drop_table("usergroup")
    op.drop_table("provider")
    # ### end Alembic commands ###
