"""REST API v1 package initialization."""

LOCATIONS_PREFIX = "/locations"
USERS_PREFIX = "/users"
IDPS_PREFIX = "/idps"
USER_GROUPS_PREFIX = "/user-groups"
SLAS_PREFIX = "/slas"
PROJECTS_PREFIX = "/projects"
PROVIDERS_PREFIX = "/providers"
REGIONS_PREFIX = "/regions"
HEALTH_PREFIX = "/health"
